# Generated by Django 3.2.11 on 2022-02-15 16:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(default='', max_length=50)),
                ('description', models.TextField(default='')),
                ('status', models.CharField(choices=[('P', 'Planning'), ('A', 'Active'), ('C', 'Control'), ('D', 'Done')], default='P', max_length=9)),
                ('previousstatus', models.CharField(choices=[('P', 'Planning'), ('A', 'Active'), ('C', 'Control'), ('D', 'Done')], max_length=9, null=True)),
                ('start_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='author', to=settings.AUTH_USER_MODEL)),
                ('changed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='changer', to=settings.AUTH_USER_MODEL)),
                ('spectators', models.ManyToManyField(null=True, related_name='spectator', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TaskChanging',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('prevstatus', models.CharField(choices=[('P', 'Planning'), ('A', 'Active'), ('C', 'Control'), ('D', 'Done')], max_length=9, null=True)),
                ('currentstatus', models.CharField(choices=[('P', 'Planning'), ('A', 'Active'), ('C', 'Control'), ('D', 'Done')], max_length=9, null=True)),
                ('changed_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('changed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('task', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stats', to='blog.task')),
            ],
        ),
        migrations.AddField(
            model_name='task',
            name='taskchange',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='blog.taskchanging'),
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.task')),
                ('users', models.ManyToManyField(null=True, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
