# Generated by Django 3.2.11 on 2022-01-26 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20220126_1630'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('P', 'Planning'), ('A', 'Active'), ('C', 'Control'), ('D', 'Done')], default='P', max_length=9),
        ),
    ]
