# Generated by Django 3.2.11 on 2022-02-03 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20220203_1137'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskhistory',
            name='nextstatus',
            field=models.CharField(choices=[('P', 'Planning'), ('A', 'Active'), ('C', 'Control'), ('D', 'Done')], max_length=9, null=True),
        ),
    ]
