# Generated by Django 3.2.11 on 2022-02-03 10:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_taskhistory_nextstatus'),
    ]

    operations = [
        migrations.RenameField(
            model_name='taskchanging',
            old_name='status',
            new_name='currentstatus',
        ),
    ]
