# Generated by Django 3.2.11 on 2022-02-03 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_rename_status_taskchanging_currentstatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='buferstatus',
            field=models.CharField(choices=[('P', 'Planning'), ('A', 'Active'), ('C', 'Control'), ('D', 'Done')], max_length=9, null=True),
        ),
    ]
