# Generated by Django 3.2.11 on 2022-02-03 16:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_remove_task_buferstatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='taskchange',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='blog.taskchanging'),
        ),
    ]
