# Generated by Django 3.2.11 on 2022-02-04 04:35

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_task_taskchange'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskchanging',
            name='changed_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
