# Generated by Django 3.2.11 on 2022-01-29 19:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_alter_task_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='taskname',
            new_name='name',
        ),
    ]
