# Generated by Django 3.2.11 on 2022-01-30 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0017_taskchanging'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('Planning', 'Planning'), ('Active', 'Active'), ('Control', 'Control'), ('Done', 'Done')], default='P', max_length=9),
        ),
    ]
