# Generated by Django 3.2.11 on 2022-01-30 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0018_alter_task_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('Planning', 'Planning'), ('Active', 'Active'), ('Control', 'Control'), ('Done', 'Done')], default='Planning', max_length=9),
        ),
    ]
