# Generated by Django 3.2.11 on 2022-01-31 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0019_alter_task_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskchanging',
            name='currentstatus',
            field=models.CharField(max_length=9, null=True),
        ),
        migrations.AlterField(
            model_name='taskchanging',
            name='prevstatus',
            field=models.CharField(max_length=9, null=True),
        ),
    ]
